[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_nft_anchor = "Ckszjv83Xxff3xRcUAzpFd8CTUkL5QXipyTo29U3LnDN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/javiermontescarrera/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
